import Head from "next/head";
import { useEffect, useState } from "react";

export default function Home() {

  const dataInit = [
    {
      pecahan: 100000,
      lembar: 0,
    },
    {
      pecahan: 50000,
      lembar: 0,
    },
    {
      pecahan: 20000,
      lembar: 0,
    },
    {
      pecahan: 10000,
      lembar: 0,
    },
    {
      pecahan: 5000,
      lembar: 0,
    },
    {
      pecahan: 2000,
      lembar: 0,
    },
    {
      pecahan: 1000,
      lembar: 0,
    },
    {
      pecahan: 500,
      lembar: 0,
    },
    {
      pecahan: 200,
      lembar: 0,
    },
    {
      pecahan: 100,
      lembar: 0,
    },
  ];

  const [data, setData] = useState(dataInit);
  const [uang, setUang] = useState("");
  const [infak, setInfak] = useState(0);

  function modulo() {
    var sisa = uang;
    const newData = data.map((value) => {
      var lembar = (sisa - (sisa % value.pecahan)) / value.pecahan;
      var pecahan = value.pecahan;
      sisa = sisa % value.pecahan;
      return {
        pecahan,
        lembar,
      };
    });
    setData(newData);
    setInfak(sisa);
  }

  useEffect(() => {
    modulo();
  }, [uang]);

  return (
    <div>
      <Head>
        <title>MATDIS MODULO</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div className="container m-8">
          <h1 className="text-3xl font-bold my-8">Matematika Diskrit Modulo</h1>
          <h3 className="font-bold">KELOMPOK : </h3>
          <ul className="text-gray-600">
            <li>▷ MUHAMMAD ADVIE RIFALDY [ 21110336 ]</li>
          </ul>

          <div className="flex flex-wrap items-end mt-8">
            <div className="form-control w-64">
              <label className="label">Uang Rp.</label>
              <input
                type="number"
                value={uang}
                onChange={(e) => {
                  setUang(e.target.value);
                }}
                placeholder="Masukan bilangan..."
                className="input input-bordered w-full"
              />
            </div>
            <button
              className="btn btn-outline btn-primary mx-2"
              onClick={() => modulo()}
            >
              Hitung
            </button>
            <button
              className="btn btn-error btn-outline text-error"
              onClick={() => setUang(" ")}
            >
              Reset
            </button>
          </div>

          <div className="overflow-x-auto mt-2">
            <table className="table table-compact">
              <thead>
                <tr>
                  <th className="w-28 text-center">Terdiri Dari</th>
                  <th className="w-36">Lembar Pecahan</th>
                </tr>
              </thead>
              <tbody>
                {data.map((value) => {
                  return (
                    <tr key={value.pecahan}>
                      <td
                        className={`text-center font-bold ${
                          value.lembar > 0 ? "" : "text-gray-300"
                        }`}
                      >
                        {value.lembar}
                      </td>
                      <td
                        className={`${value.lembar > 0 ? "" : "text-gray-300"}`}
                      >
                        Rp. {value.pecahan}
                      </td>
                    </tr>
                  );
                })}
                <tr>
                  <th>Infak:</th>
                  <td>Rp. {infak}</td>
                </tr>
              </tbody>
            </table>
          </div>
        </div>
      </main>
    </div>
  );
}
